export const formats = [
  {
    name: "android",
    items: [
      {
        name: "mipmap-hdpi",
        items: [
          {
            width: 72,
            height: 72,
            radius: false,
            type: "PNG",
            name: "ic_launcher.png",
          },
          {
            width: 72,
            height: 72,
            radius: true,
            type: "PNG",
            name: "ic_launcher_round.png",
          },
        ],
      },
      {
        name: "mipmap-mdpi",
        items: [
          {
            width: 48,
            height: 48,
            radius: true,
            type: "PNG",
            name: "ic_launcher_round.png",
          },
          {
            width: 48,
            height: 48,
            radius: false,
            type: "PNG",
            name: "ic_launcher.png",
          },
        ],
      },
      {
        name: "mipmap-xhdpi",
        items: [
          {
            width: 96,
            height: 96,
            radius: true,
            type: "PNG",
            name: "ic_launcher_round.png",
          },
          {
            width: 96,
            height: 96,
            radius: false,
            type: "PNG",
            name: "ic_launcher.png",
          },
        ],
      },
      {
        name: "mipmap-xxhdpi",
        items: [
          {
            width: 144,
            height: 144,
            radius: true,
            type: "PNG",
            name: "ic_launcher_round.png",
          },
          {
            width: 144,
            height: 144,
            radius: false,
            type: "PNG",
            name: "ic_launcher.png",
          },
        ],
      },
      {
        name: "mipmap-xxxhdpi",
        items: [
          {
            width: 192,
            height: 192,
            radius: true,
            type: "PNG",
            name: "ic_launcher_round.png",
          },
          {
            width: 192,
            height: 192,
            radius: false,
            type: "PNG",
            name: "ic_launcher.png",
          },
        ],
      },
    ],
  },
  {
    name: "ios",
    items: [
      {
        name: "iphone",
        items: [
          {
            width: 40,
            height: 40,
            radius: false,
            type: "JPG",
            name: "40_40_AppIcon.jpg",
          },
          {
            width: 60,
            height: 60,
            radius: false,
            type: "JPG",
            name: "60_60_AppIcon.jpg",
          },
          {
            width: 58,
            height: 58,
            radius: false,
            type: "JPG",
            name: "58_58_AppIcon.jpg",
          },
          {
            width: 87,
            height: 87,
            radius: false,
            type: "JPG",
            name: "87_87_AppIcon.jpg",
          },
          {
            width: 80,
            height: 80,
            radius: false,
            type: "JPG",
            name: "80_80_AppIcon.jpg",
          },
          {
            width: 120,
            height: 120,
            radius: false,
            type: "JPG",
            name: "120_120_AppIcon.jpg",
          },
          {
            width: 180,
            height: 180,
            radius: false,
            type: "JPG",
            name: "180_180_AppIcon.jpg",
          },
          {
            width: 1024,
            height: 1024,
            radius: false,
            type: "JPG",
            name: "1024_1024_AppIcon.jpg",
          },
        ],
      },
      {
        name: "ipad",
        items: [
          {
            width: 167,
            height: 167,
            radius: false,
            type: "JPG",
            name: "167_167_AppIcon.jpg",
          },
          {
            width: 152,
            height: 152,
            radius: false,
            type: "JPG",
            name: "152_152_AppIcon.jpg",
          },
          {
            width: 80,
            height: 80,
            radius: false,
            type: "JPG",
            name: "80_80_AppIcon.jpg",
          },
          {
            width: 120,
            height: 120,
            radius: false,
            type: "JPG",
            name: "120_120_AppIcon.jpg",
          },
          {
            width: 58,
            height: 58,
            radius: false,
            type: "JPG",
            name: "58_58_AppIcon.jpg",
          },
          {
            width: 87,
            height: 87,
            radius: false,
            type: "JPG",
            name: "87_87_AppIcon.jpg",
          },
          {
            width: 76,
            height: 76,
            radius: false,
            type: "JPG",
            name: "76_76_AppIcon.jpg",
          },
          {
            width: 114,
            height: 114,
            radius: false,
            type: "JPG",
            name: "114_114_AppIcon.jpg",
          },
        ],
      },
      {
        name: "macOS",
        items: [
          {
            width: 512,
            height: 512,
            radius: false,
            type: "JPG",
            name: "512_512_AppIcon.jpg",
          },
          {
            width: 1024,
            height: 1024,
            radius: false,
            type: "JPG",
            name: "1024_1024_AppIcon.jpg",
          },
          {
            width: 256,
            height: 256,
            radius: false,
            type: "JPG",
            name: "256_256_AppIcon.jpg",
          },
          {
            width: 512,
            height: 512,
            radius: false,
            type: "JPG",
            name: "512_512_AppIcon.jpg",
          },
          {
            width: 128,
            height: 128,
            radius: false,
            type: "JPG",
            name: "128_128_AppIcon.jpg",
          },
          {
            width: 32,
            height: 32,
            radius: false,
            type: "JPG",
            name: "32_32_AppIcon.jpg",
          },
          {
            width: 64,
            height: 64,
            radius: false,
            type: "JPG",
            name: "64_64_AppIcon.jpg",
          },
          {
            width: 16,
            height: 16,
            radius: false,
            type: "JPG",
            name: "16_16_AppIcon.jpg",
          },
          {
            width: 32,
            height: 32,
            radius: false,
            type: "JPG",
            name: "32_32_AppIcon.jpg",
          },
        ],
      },
      {
        name: "tvOS",
        items: [
          {
            width: 400,
            height: 240,
            radius: false,
            type: "JPG",
            name: "400_240_AppIcon.jpg",
          },
          {
            width: 800,
            height: 480,
            radius: false,
            type: "JPG",
            name: "800_480_AppIcon.jpg",
          },
        ],
      },
      {
        name: "watchOS",
        items: [
          {
            width: 80,
            height: 80,
            radius: false,
            type: "JPG",
            name: "80_80_AppIcon.jpg",
          },
          {
            width: 88,
            height: 88,
            radius: false,
            type: "JPG",
            name: "88_88_AppIcon.jpg",
          },
          {
            width: 92,
            height: 92,
            radius: false,
            type: "JPG",
            name: "92_92_AppIcon.jpg",
          },
          {
            width: 100,
            height: 100,
            radius: false,
            type: "JPG",
            name: "100_100_AppIcon.jpg",
          },
          {
            width: 102,
            height: 102,
            radius: false,
            type: "JPG",
            name: "102_102_AppIcon.jpg",
          },
          {
            width: 108,
            height: 108,
            radius: false,
            type: "JPG",
            name: "108_108_AppIcon.jpg",
          },
          {
            width: 48,
            height: 48,
            radius: false,
            type: "JPG",
            name: "48_48_AppIcon.jpg",
          },
          {
            width: 55,
            height: 55,
            radius: false,
            type: "JPG",
            name: "55_55_AppIcon.jpg",
          },
          {
            width: 58,
            height: 58,
            radius: false,
            type: "JPG",
            name: "58_58_AppIcon.jpg",
          },
          {
            width: 66,
            height: 66,
            radius: false,
            type: "JPG",
            name: "66_66_AppIcon.jpg",
          },
          {
            width: 172,
            height: 172,
            radius: false,
            type: "JPG",
            name: "172_172_AppIcon.jpg",
          },
          {
            width: 196,
            height: 196,
            radius: false,
            type: "JPG",
            name: "196_196_AppIcon.jpg",
          },
          {
            width: 216,
            height: 216,
            radius: false,
            type: "JPG",
            name: "216_216_AppIcon.jpg",
          },
          {
            width: 234,
            height: 234,
            radius: false,
            type: "JPG",
            name: "234_234_AppIcon.jpg",
          },
          {
            width: 258,
            height: 258,
            radius: false,
            type: "JPG",
            name: "258_258_AppIcon.jpg",
          },
        ],
      },
    ],
  },
];
